#!/usr/bin/env ruby

require "gitlab/release/changelog/generator"
require 'dotenv'

Dotenv.load('../.env')

endpoint = ENV["GITLAB_BASE_URL"]
private_token = ENV["PRIVATE_TOKEN"]

generator = Gitlab::Release::Changelog::Generator.new(endpoint, private_token)

changelog = generator.changelog("10.0", project_id: 278964)

print(changelog.as_string(true))
changelog.write_on_file('../result.txt', true)
